name: 'Grenades'
description: 'TODO'
author: Turtle
load: STARTUP
version: 1.8.6
api-version: 1.20
main: dev.turtle.grenades.Main
softdepend: [CoreProtect, NBTAPI]
commands:
    grenade:
        aliases: [g]
        description: Main command
permissions:
    grenades.cooldown.bypass:
        description: Allows using grenades without cooldown